language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g bower
env:
  global:
    - secure: lce4c2Ud9uKCuz4+6M+hFvatNZU+jLlLm5JVfagOgE8yJ4PwuVCeFBNm64d26HNvHJ77HwfcRCmHI5ZHSkOlbWg571Q+iO2lNZ9+o8D+cS5yGTMb4Zcj2OSqgyo932Q8lI4VsYYkIULRFoWAseETdGOOLaeKAvmeaWtRXJQI2B4=
    - secure: HCsAMPNlLyjL3RfQA7kheU/7fi4bPd+ozrR/29VhT1D7x5BW0p8yNQxg6wrY96xZFgKjdCaKcioJQzVs5QC1Y/4fxjGir/JzIZimZdQ/MiA71GeKYXwbP6fJaA4HikZBUYHq+L/8EUHz0bL/jSJBm5SN+d9Lh3EmHprYjTX/fHU=
addons:
  sauce_connect: true
